export const WRITE_AVAILABLE_STATUSES = 'WRITE_AVAILABLE_STATUSES';
export const UPDATE_THE_TIMESTAMP = "UPDATE_THE_TIMESTAMP";
export const GET_EVENT_USER_AGG_TIMES = "GET_EVENT_USER_AGG_TIMES";
export const DETERMINE_WEEKDAY = "DETERMINE_WEEKDAY"
export const UPDATE_EVENT_DURATION = "UPDATE_EVENT_DURATION"
